name: CI for express api

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build-and-test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: pnpm adding
        uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: "9.7.1"
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm run test
# - name: Upload test results (optional)
#   if: failure()
#   uses: actions/upload-artifact@v4
#   with:
#     name: test-results
#     path: test-results/*
